# Welcome to Serverless!
#
# For full config options, check the kubeless plugin docs:
#    https://github.com/serverless/serverless-kubeless
#
# For documentation on kubeless itself:
#    http://kubeless.io

# Update the service name below with your own service name
service: customer-service

# Please ensure the serverless-kubeless provider plugin is installed globally.
# $ npm install -g serverless-kubeless
#
# ...before installing project dependencies to register this provider.
# $ npm install

provider:
  name: kubeless
  runtime: python3.6
  environment:
    MONGO-URL: "mongodb://db:27017"
    SSL_DEBUG: "*"
package:
  exclude:
    - venv/**
    - node_modules/**
    - .idea/**
   
plugins:
  - serverless-kubeless

functions:
  createcustomer:
    handler: customerhandler.savecustomer
    events:
      - http:
          path: /savecustomer
          hostname: ${env:SERVER-HOST}

  getcustomer:
    handler: customerhandler.getcustomer
    events:
    - http:
        path: /getcustomer
        hostname: ${env:SERVER-HOST}

  deletecustomer:
    handler: customerhandler.deletecustomer
    events:
    - http:
        path: /deletecustomer
        hostname: ${env:SERVER-HOST}
